const strings = {
  retro: {
    appTitle: "PIXEL POMO",
    navPlay: "\uD83C\uDFAE PLAY",
    navStats: "\u2B50 STATS",
    questLog: "\u2694 QUEST LOG",
    currentQuest: "\u2694 CURRENT QUEST",
    newTaskPlaceholder: "NEW QUEST...",
    noTasks: "NO QUESTS YET",
    noTasksSub: "ADD ONE ABOVE!",
    clickToFocus: "\u2191 CLICK A QUEST TO FOCUS \u2191",
    focusSubtext: "SELECT YOUR TARGET!",
    openBoard: "\u2630 OPEN FULL QUEST BOARD",
    closeBoard: "\u2716 CLOSE BOARD",
    sessionComplete: "\u2605 SESSION COMPLETE! \u2605",
    breakOver: ">> BREAK OVER!",
    readyFor: "READY FOR",
    taskComplete: "QUEST COMPLETE?",
    taskLabel: "QUEST",
    xpGain: (mins) => `+${mins} XP`,
    startBtn: ">> START",
    resumeBtn: ">> RESUME",
    pauseBtn: "|| PAUSE",
    resetBtn: "<< RESET",
    startAnyway: "START ANYWAY >>",
    focusPromptTitle: "WHAT ARE YOU WORKING ON?",
    focusPromptSub: "SELECT A QUEST OR START WITHOUT ONE",
    columnTodo: "TO DO",
    columnInProgress: "IN PROGRESS",
    columnDone: "DONE",
    emptyTodo: "NO QUESTS YET",
    emptyTodoSub: "ADD ONE ABOVE!",
    emptyInProgress: "DRAG TASKS",
    emptyInProgressSub: "HERE",
    emptyDone: "COMPLETED",
    emptyDoneSub: "QUESTS",
    completed: "COMPLETED",
    footer: "PIXEL POMO v2.0 \u2665 STAY FOCUSED, ADVENTURER!",
    todayLabel: "TODAY",
    focusLabel: "FOCUS",
    streakLabel: "STREAK",
    tasksLabel: "TASKS",
    last7Days: "\u2593 LAST 7 DAYS \u2593",
    sessionLog: "\u2593 SESSION LOG \u2593",
    noSessions: "NO SESSIONS RECORDED YET",
    noSessionsSub: "COMPLETE A POMODORO TO SEE YOUR LOG!",
    sessionEntry: (n) => `\u2665 SESSION #${n}`,
    todaySessions: "TODAY'S SESSIONS",
    focusTime: "FOCUS TIME",
    currentStreak: "CURRENT STREAK",
    allTimeSessions: "ALL-TIME SESSIONS",
    totalFocusTime: "TOTAL FOCUS TIME",
    minutes: "MINUTES",
    done: "DONE",
    focused: "FOCUSED",
    focus: "FOCUS",
    yesBtn: "\u2713 YES!",
    notYetBtn: "NOT YET",
    skipBtn: "SKIP",
  },
  clean: {
    appTitle: "Pomo",
    navPlay: "Timer",
    navStats: "Stats",
    questLog: "Tasks",
    currentQuest: "Current Task",
    newTaskPlaceholder: "Add a task...",
    noTasks: "No tasks yet",
    noTasksSub: "Add one above",
    clickToFocus: "Click a task to focus on it",
    focusSubtext: "Pick your next priority",
    openBoard: "Open Task Board",
    closeBoard: "Close Board",
    sessionComplete: "Session Complete!",
    breakOver: "Break's over!",
    readyFor: "Ready for",
    taskComplete: "Did you finish this task?",
    taskLabel: "Task",
    xpGain: (mins) => `${mins} min focused`,
    startBtn: "Start",
    resumeBtn: "Resume",
    pauseBtn: "Pause",
    resetBtn: "Reset",
    startAnyway: "Start without a task",
    focusPromptTitle: "What will you work on?",
    focusPromptSub: "Pick a task or start without one",
    columnTodo: "To Do",
    columnInProgress: "In Progress",
    columnDone: "Done",
    emptyTodo: "No tasks yet",
    emptyTodoSub: "Add one above",
    emptyInProgress: "Drag tasks here",
    emptyInProgressSub: "",
    emptyDone: "Completed tasks",
    emptyDoneSub: "",
    completed: "Completed",
    footer: "Pomo \u2014 Stay focused.",
    todayLabel: "Today",
    focusLabel: "Focus",
    streakLabel: "Streak",
    tasksLabel: "Tasks",
    last7Days: "Last 7 Days",
    sessionLog: "Session Log",
    noSessions: "No sessions recorded yet.",
    noSessionsSub: "Complete a pomodoro to see your log.",
    sessionEntry: (n) => `Session #${n}`,
    todaySessions: "Today's Sessions",
    focusTime: "Focus Time",
    currentStreak: "Current Streak",
    allTimeSessions: "All-Time Sessions",
    totalFocusTime: "Total Focus Time",
    minutes: "minutes",
    done: "done",
    focused: "Focused",
    focus: "Focus",
    yesBtn: "Yes, done!",
    notYetBtn: "Not yet",
    skipBtn: "Skip",
  },
};

export default strings;
